jobs:

# jobs for the dv pipeline from CI thru TEST environment


# manifest gen for VISUALIZER
  - name: demo-man
    type: manifest
    steps:
      - IN: demo-img
      - IN: demo-img-opts
      - TASK: managed

#/ manifest gen for VISUALIZER

# TEST deployment for VISUALIZER to Amazon ECS
  - name: demo-test-ecs
    type: deploy
    steps:
      - IN: demo-man
#      - IN: demo-params
      - IN: env-ecs
      - TASK: managed

# / TEST deployment for VISUALIZER to Amazon ECS
